CC = g++
OBJECTS = main.o Graph.o

all: $(OBJECTS)
	$(CC) $(OBJECTS) -o main
clean:
	rm *.o main
#dijkstra:
#	./main dijkstra $(filter-out $@, $(MAKECMDGOALS))
#dial:
#	./main dial $(filter-out $@, $(MAKECMDGOALS))
#radixheap:
#	./main radixheap $(filter-out $@, $(MAKECMDGOALS))
#%:
#	@true